[package]
name = "rust-bcc-tools"
version = "0.1.0"
authors = ["Ricardo Delfin <me@rdelfin.com>"]
edition = "2018"

[dependencies]
bcc = "0.0.13"
byteorder = "1.3.4"
clap = "2.33.0"
ctrlc = "3.1.3"
failure = "0.1.6"
libc = "0.2.66"
