[package]
name = "rust-bcc-tools"
version = "0.1.0"
authors = ["Ricardo Delfin <me@rdelfin.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.33"
bcc = "0.0.29"
byteorder = "1.3.4"
clap = "2.33.0"
ctrlc = "3.1.3"
libc = "0.2.66"
