[package]
name = "rust-bcc-tools"
version = "0.1.0"
authors = ["Ricardo Delfin <me@rdelfin.com>"]
edition = "2018"

[[bin]]
name = "opensnoop"

[[bin]]
name = "execsnoop"

[dependencies]
anyhow = "1.0"
bcc = "0.0.31"
byteorder = "1.4"
structopt = "0.3"
ctrlc = "3.2"
libc = "0.2"
